// =============================================
// lib/events.js — Central Event Metadata
// =============================================
const EVENTS = [
    // DAY 1: AWAKENING — 22 April
    { eventId:'valhalla',  key:'VALHALLA',  norseName:'Valhalla',  commonName:'E-Games',             arenaName:'Awakening', eventDate:'22 April 2026', day:1, startTime:'09:00', endTime:'11:00', sM:540,  eM:660,  minMembers:4, maxMembers:4, imagePath:'Assets/valhalla.png',  isOfflineOnly:false, isConflictException:false, hasRulebook:true, hasRegistration:true, rune:'ᚠ', desc:'Enter the digital colosseum. Compete in the ultimate gaming trials and prove your mastery in the electronic arena.' },
    { eventId:'helheim',   key:'HELHEIM',   norseName:'Helheim',   commonName:'Escape Room',          arenaName:'Awakening', eventDate:'22 April 2026', day:1, startTime:'09:00', endTime:'15:00', sM:540,  eM:900,  minMembers:3, maxMembers:3, imagePath:'Assets/helheim.png',   isOfflineOnly:false, isConflictException:true,  hasRulebook:true, hasRegistration:true, rune:'ᚢ', desc:'Venture into the shadowed realm. Solve cryptic puzzles, decode ancient mysteries, and escape the labyrinth before time runs out.' },
    { eventId:'saga',      key:'SAGA',      norseName:'Saga',      commonName:'Quiz',                 arenaName:'Awakening', eventDate:'22 April 2026', day:1, startTime:'11:15', endTime:'12:15', sM:675,  eM:735,  minMembers:1, maxMembers:2, imagePath:'Assets/saga.png',      isOfflineOnly:false, isConflictException:false, hasRulebook:true, hasRegistration:true, rune:'ᚦ', desc:'Channel the wisdom of the ages. Test your knowledge across technology, science, and engineering.' },
    { eventId:'eitri',     key:'EITRI',     norseName:'Eitri',     commonName:'Project Expo',         arenaName:'Awakening', eventDate:'22 April 2026', day:1, startTime:'12:20', endTime:'14:00', sM:740,  eM:840,  minMembers:1, maxMembers:3, imagePath:'Assets/eitri.png',     isOfflineOnly:false, isConflictException:false, hasRulebook:true, hasRegistration:true, rune:'ᛇ', desc:'Present the fruits of your forge. Showcase your technical projects, innovations, and research.' },
    { eventId:'seidr',     key:'SEIDR',     norseName:'Seidr',     commonName:'Reverse Engineering',  arenaName:'Awakening', eventDate:'22 April 2026', day:1, startTime:'12:30', endTime:'13:30', sM:750,  eM:810,  minMembers:1, maxMembers:2, imagePath:'Assets/seidr.png',     isOfflineOnly:false, isConflictException:false, hasRulebook:true, hasRegistration:true, rune:'ᚱ', desc:'Unravel the ancient code. Dissect, analyze, and reconstruct — a trial of deep technical mastery.' },
    { eventId:'runes',     key:'RUNES',     norseName:'Runes',     commonName:'Spell Bee',            arenaName:'Awakening', eventDate:'22 April 2026', day:1, startTime:'12:30', endTime:'13:30', sM:750,  eM:810,  minMembers:1, maxMembers:1, imagePath:'Assets/runes.png',     isOfflineOnly:false, isConflictException:false, hasRulebook:true, hasRegistration:true, rune:'ᚹ', desc:'Command the power of language itself. Spell your way to victory through technical jargon.' },
    { eventId:'runecraft', key:'RUNECRAFT', norseName:'Runecraft', commonName:'Coding',               arenaName:'Awakening', eventDate:'22 April 2026', day:1, startTime:'09:00', endTime:'11:00', sM:540,  eM:660,  minMembers:1, maxMembers:1, imagePath:'Assets/runecraft.png', isOfflineOnly:false, isConflictException:false, hasRulebook:true, hasRegistration:true, rune:'ᚷ', desc:'Forge solutions from pure logic. Write elegant, efficient code to conquer algorithmic challenges.' },
    { eventId:'bifrost',   key:'BIFROST',   norseName:'Bifrost',   commonName:'Treasure Hunt',        arenaName:'Awakening', eventDate:'22 April 2026', day:1, startTime:'14:30', endTime:'17:30', sM:870,  eM:1050, minMembers:4, maxMembers:4, imagePath:'Assets/bifrost.png',   isOfflineOnly:false, isConflictException:false, hasRulebook:true, hasRegistration:true, rune:'ᚲ', desc:'Follow the rainbow bridge across the campus. Decode clues and navigate the hidden pathways of SSIT.' },
    // DAY 2: RAGNAROK — 23 April
    { eventId:'volva',     key:'VOLVA',     norseName:'Volva',     commonName:'Kaggle Competition',   arenaName:'Ragnarök',  eventDate:'23 April 2026', day:2, startTime:'09:00', endTime:'11:00', sM:540,  eM:660,  minMembers:1, maxMembers:1, imagePath:'Assets/volva.png',     isOfflineOnly:false, isConflictException:false, hasRulebook:true, hasRegistration:true, rune:'ᚨ', desc:'Wield the magic of data. Craft predictive models, analyze hidden patterns.' },
    { eventId:'yggdrasil', key:'YGGDRASIL', norseName:'Yggdrasil', commonName:'Web Design',           arenaName:'Ragnarök',  eventDate:'23 April 2026', day:2, startTime:'09:00', endTime:'11:00', sM:540,  eM:660,  minMembers:1, maxMembers:1, imagePath:'Assets/yggdrasil.png', isOfflineOnly:false, isConflictException:false, hasRulebook:true, hasRegistration:true, rune:'ᚺ', desc:'Build the digital world tree. Design stunning, functional websites.' },
    { eventId:'mimir',     key:'MIMIR',     norseName:'Mimir',     commonName:'Shark Tank',           arenaName:'Ragnarök',  eventDate:'23 April 2026', day:2, startTime:'10:00', endTime:'12:00', sM:600,  eM:720,  minMembers:2, maxMembers:4, imagePath:'Assets/mimir.png',     isOfflineOnly:false, isConflictException:true,  hasRulebook:true, hasRegistration:true, rune:'ᚾ', desc:'Pitch your innovation to the council of wisdom. Present your startup idea.' },
    { eventId:'jotunn',    key:'JOTUNN',    norseName:'Jotunn',    commonName:'Robo War',             arenaName:'Ragnarök',  eventDate:'23 April 2026', day:2, startTime:'13:00', endTime:'15:00', sM:780,  eM:900,  minMembers:1, maxMembers:1, imagePath:'Assets/jotunn.png',    isOfflineOnly:false, isConflictException:false, hasRulebook:true, hasRegistration:true, rune:'ᛁ', desc:'Unleash your mechanical giant. Engineer battle robots for the ultimate arena test.' },
    { eventId:'sleipnir',  key:'SLEIPNIR',  norseName:'Sleipnir',  commonName:'Robo Race / LFR',     arenaName:'Ragnarök',  eventDate:'23 April 2026', day:2, startTime:'13:00', endTime:'15:00', sM:780,  eM:900,  minMembers:1, maxMembers:1, imagePath:'Assets/sleipnir.png',  isOfflineOnly:false, isConflictException:false, hasRulebook:true, hasRegistration:true, rune:'ᛃ', desc:'Build the eight-legged steed of innovation. Line-following robots that race with precision.' },
    { eventId:'loki',      key:'LOKI',      norseName:'Loki',      commonName:'Crime Investigation',  arenaName:'Ragnarök',  eventDate:'23 April 2026', day:2, startTime:'15:00', endTime:'17:00', sM:900,  eM:1020, minMembers:2, maxMembers:4, imagePath:'Assets/loki.png',      isOfflineOnly:false, isConflictException:false, hasRulebook:true, hasRegistration:true, rune:'ᛈ', desc:'The trickster has struck — can you unveil the truth? Analyze evidence, question suspects.' },
    { eventId:'skald',     key:'SKALD',     norseName:'Skald',     commonName:'Cinematography',       arenaName:'Ragnarök',  eventDate:'23 April 2026', day:2, startTime:'15:00', endTime:'16:30', sM:900,  eM:990,  minMembers:1, maxMembers:2, imagePath:'Assets/skald.png',     isOfflineOnly:false, isConflictException:false, hasRulebook:true, hasRegistration:true, rune:'ᛉ', desc:'Tell the tale through moving images. Craft compelling short films.' },
    // BOTH DAYS
    { eventId:'folkvangr', key:'FOLKVANGR', norseName:'Folkvangr', commonName:'Fun Games',            arenaName:'Folkvangr', eventDate:'22 & 23 April', day:0, startTime:null,    endTime:null,    sM:0,    eM:0,    minMembers:1, maxMembers:1, imagePath:'Assets/folkvangr.png', isOfflineOnly:true,  isConflictException:true,  hasRulebook:false,hasRegistration:false,rune:'ᛊ', desc:'Enter the field of the people — where joy and camaraderie reign. Offline registrations on spot.' }
];

function getEvent(id) { return EVENTS.find(e => e.eventId === id) || null; }
function getAllEvents() { return EVENTS; }
module.exports = { EVENTS, getEvent, getAllEvents };
